export const PATTERNS = Object.freeze(
  [
    { id: "horizontal_push", name: "水平推" },
    { id: "vertical_push", name: "垂直推" },
    { id: "vertical_pull", name: "垂直拉" },
    { id: "horizontal_pull", name: "水平拉" },
    { id: "knee_dominant", name: "膝主導" },
    { id: "hip_hinge", name: "髖鉸鏈" },
    { id: "hip_extension", name: "髖伸展" },
    { id: "knee_flexion", name: "屈膝" },
    { id: "core_anti_extension", name: "核心抗伸展" },
    { id: "core_anti_rotation", name: "核心抗旋轉" },
    { id: "single_leg_balance", name: "單腳平衡" },
    { id: "ankle", name: "踝與小腿" },
    { id: "elbow_flexion", name: "肘屈曲" },
    { id: "hip_adduction", name: "髖內收" },
    { id: "hip_abduction", name: "髖外展" },
  ].map(Object.freeze),
);

export const EXERCISES = Object.freeze(
  [
    {id:'abdominal_bracing',name:'仰躺輕收腹呼吸',pattern:'core_anti_extension',metric:'bodyweight'},
    {
      id: "biceps_curl",
      name: "坐姿二頭彎舉",
      pattern: "elbow_flexion",
      metric: "load",
    },
    {
      id: "incline_chest_press",
      name: "上斜胸推",
      pattern: "horizontal_push",
      metric: "load",
    },
    {
      id: "hip_adduction",
      name: "髖內收",
      pattern: "hip_adduction",
      metric: "load",
    },
    {
      id: "hip_abduction",
      name: "髖外展",
      pattern: "hip_abduction",
      metric: "load",
    },
    {
      id: "v_squat",
      name: "V-Squat 槓桿深蹲",
      pattern: "knee_dominant",
      metric: "load",
    },
    { id: "leg_press", name: "腿推", pattern: "knee_dominant", metric: "load" },
    {
      id: "leg_extension",
      name: "腿伸展",
      pattern: "knee_dominant",
      metric: "load",
    },
    { id: "leg_curl", name: "腿彎舉", pattern: "knee_flexion", metric: "load" },
    {
      id: "chest_press",
      name: "胸推",
      pattern: "horizontal_push",
      metric: "load",
    },
    {
      id: "seated_row",
      name: "坐姿划船",
      pattern: "horizontal_pull",
      metric: "load",
    },
    {
      id: "lat_pulldown",
      name: "滑輪下拉",
      pattern: "vertical_pull",
      metric: "load",
    },
    {
      id: "shoulder_press",
      name: "肩推",
      pattern: "vertical_push",
      metric: "load",
    },
    {
      id: "assisted_pull_up",
      name: "輔助正握引體向上",
      pattern: "vertical_pull",
      metric: "assistance",
    },
    {
      id: "assisted_chinup",
      name: "輔助反握引體向上",
      pattern: "vertical_pull",
      metric: "assistance",
    },
    {
      id: "assisted_dip",
      name: "輔助雙槓撐體",
      pattern: "vertical_push",
      metric: "assistance",
    },
    {
      id: "squat",
      name: "徒手深蹲",
      pattern: "knee_dominant",
      metric: "bodyweight",
    },
    { id: "hip_hinge", name: "髖鉸鏈", pattern: "hip_hinge", metric: "load" },
    {
      id: "glute_bridge",
      name: "臀橋",
      pattern: "hip_extension",
      metric: "bodyweight",
    },
    {
      id: "pallof_press",
      name: "Pallof 抗旋轉推",
      pattern: "core_anti_rotation",
      metric: "load",
    },
    {
      id: "single_leg_balance",
      name: "單腳平衡（每次完成）",
      pattern: "single_leg_balance",
      metric: "bodyweight",
    },
    { id: "calf_raise", name: "提踵", pattern: "ankle", metric: "load" },
    {
      id: "dead_bug",
      name: "死蟲式",
      pattern: "core_anti_extension",
      metric: "bodyweight",
    },
  ].map(Object.freeze),
);

export const INBODY_FIELDS = Object.freeze(
  [
    { optional: true, id: "segmental_right_arm_pct", label: "右臂 Lean 參考比", unit: "%" },
    { optional: true, id: "segmental_trunk_pct", label: "軀幹 Lean 參考比", unit: "%" },
    { optional: true, id: "inbody_score", label: "InBody 評分", unit: "分" },
    { optional: true, id: "bmr", label: "基礎代謝估計 BMR", unit: "kcal/day" },
    { optional: true, id: "smi", label: "SMI", unit: "kg/m²" },
    {
      optional: true,
      id: "waist_hip_ratio",
      label: "腰臀比 WHR",
      unit: "比值",
    },
    { optional: true, id: "total_body_water", label: "總身體水分", unit: "L" },
    { optional: true, id: "protein_mass", label: "蛋白質量", unit: "kg" },
    { optional: true, id: "mineral_mass", label: "礦物質量", unit: "kg" },
    {
      optional: true,
      id: "segmental_trunk_fat",
      label: "軀幹脂肪量",
      unit: "kg",
    },
    {
      optional: true,
      id: "segmental_trunk_fat_pct",
      label: "軀幹脂肪參考比",
      unit: "%",
    },
    {
      optional: true,
      id: "segmental_left_arm_pct",
      label: "左臂 Lean 參考比",
      unit: "%",
    },
    {
      optional: true,
      id: "segmental_left_leg_pct",
      label: "左腿 Lean 參考比",
      unit: "%",
    },
    {
      optional: true,
      id: "segmental_right_leg_pct",
      label: "右腿 Lean 參考比",
      unit: "%",
    },
    { id: "weight", label: "體重", unit: "kg" },
    { id: "skeletal_muscle_mass", label: "骨骼肌重", unit: "kg" },
    { id: "body_fat_mass", label: "體脂肪重", unit: "kg" },
    { id: "body_fat_percentage", label: "體脂率", unit: "%" },
    { id: "fat_free_mass", label: "除脂體重", unit: "kg" },
    { id: "bmi", label: "BMI", unit: "kg/m²" },
    { id: "visceral_fat_level", label: "內臟脂肪等級", unit: "級" },
    { id: "segmental_left_arm", label: "左臂部位 Lean（原始值）", unit: "kg" },
    { id: "segmental_right_arm", label: "右臂部位 Lean（原始值）", unit: "kg" },
    { id: "segmental_left_leg", label: "左腿部位 Lean（原始值）", unit: "kg" },
    { id: "segmental_right_leg", label: "右腿部位 Lean（原始值）", unit: "kg" },
    { id: "segmental_trunk", label: "軀幹部位 Lean（原始值）", unit: "kg" },
  ].map(Object.freeze),
);
